### ISSUE TITLE
Clear Queue not functional in latest master

### ISSUE THREAD

**Issue by archphile** [jcorporation/myMPD#18]
Hi Jcorporation,

I built and using mympd (under ArchlinuxARM) from latest master/  

I noticed that "clear queue" button in queue tab is not functional.

Steps to reproduce:

- Load any file from your library
- Go to queue tab
- Press the clear queue button.

I tested it with various browsers with the same results.

Regards,

Mike

**Comment by jcorporation** [comment]
The bug is now fixed. The shuffle button was also fixed. 

Sorry, but the latest master is not as stable as it should be. Currently I remastering much of the javascript in devel to bring the advanced actions live. If this branche is merged into master, the main big changes for myMPD are done and it will become more stable.

**Comment by archphile** [comment]
Many thanks for the immediate fix.

Regards,
Mike
