### ISSUE TITLE
albumcache not ready after update to 6.12

### ISSUE THREAD

**Issue by payback007** [jcorporation/myMPD#450]
After upgrade from version 6.11_devel to 6.12 there is an error with "albumcache not ready" again.

<img width="179" alt="Bildschirmfoto 2021-03-16 um 20 50 44" src="https://user-images.githubusercontent.com/25882000/111371687-09a7a780-869a-11eb-8d1f-040c2db59e8d.png">

Seem to be the same as already reported: https://github.com/jcorporation/myMPD/issues/419

**Comment by jcorporation** [comment]
Please attach debug log of myMPD.

**Comment by payback007** [comment]
Don't know what I did, but tried it several times to repeat, no errors on albumcache any more. But there are several warnings:

[konsole_log.txt](https://github.com/jcorporation/myMPD/files/6166903/konsole_log.txt)

**Comment by jcorporation** [comment]
The first error: `[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (192.168.1.109, line 0)`. could be the reason for the warnings. Probably an extension causes this. myMPD has a strict content security policy set to prevent XSS.

I close this issue now. Feel free to reopen it, if you can reproduce it.
